### ISSUE TITLE
Updated 0 items

### ISSUE THREAD

**Issue by pjeby** [Instapaper/obsidian-instapaper#48]
I installed the plugin, logged in, and whenever I use the sync command I get "Updated 0 items".  As in, there are no items, despite me having plenty in Instapaper.  I tried adding a new item to IP to see if that made a difference.  Hourly or manual, "Sync on start" enabled and disabled, no combination of these settings or manual sync commands produced any updates whatsoever.

Is this a premium-only feature, or something?  If so, I didn't see it mentioned in the README or the plugin announcement.  Thanks.

**Comment by petermakowski** [comment]
I do have premium, but have the same issue.

**Comment by Donohue** [comment]
@pjeby and @petermakowski – thanks for getting in touch. The Instapaper Obsidian plugin syncs only your highlights and notes, not all of your Instapaper articles. Just want to make sure that's clear.

If you have successfully connected and your highlights/notes are not syncing properly, can you please email us at support@help.instapaper.com so we can take a look at your account?

**Comment by Donohue** [comment]
@pjeby @petermakowski which platform are you using Obsidian on? (e.g. Windows/Mac/iOS/Android)

**Comment by pjeby** [comment]
Windows.  But I didn't even know highlights and notes existed, so I was only looking for article sync.

**Comment by Donohue** [comment]
Thanks @pjeby – we'll consider adding article sync in the future.

@petermakowski if you're running on Windows and trying to sync notes, version 1.0.6 fixes the syncing issues on Windows.
